name: test
on:
  push:
  pull_request:

env: 
  GO_VERSION: 1.22.8

jobs: 
  run-tests:
    name: Run tests 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - shell: bash 
        run: |
          go test -v
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: ${{ env.GO_VERSION }}
           go-package: ./...